apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: razorsecure-cloud
  namespace: default
spec:
  releaseName: razor
  chart:
    spec:
      chart: razorsecure-cloud
      sourceRef:
        kind: HelmRepository
        name: razorsecure-cloud
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
