---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: razorsecure-cloud
  namespace: default
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/johnscarrott
  type: "oci"
  secretRef:
    name: docker-hub-helm-credentials
